### ISSUE TITLE
Missing Dependency on update-list

### ISSUE THREAD

**Issue by uniibu** [danneu/cloudflare-ip#1]
Running update-list via node will result in a missing dependency error. It is missing 'node-fetch' module.

Also If cloudflare-ip is installed via npm install cloudflare-ip --save, the location of update-list will be at ./node_modules/cloudflare-ip/update-list, therefor running npm run update-list on the app's root directory will not work.

What i did was install node-fetch (npm i node-fetch --save)
then ran (node ./node_modules/cloudflare-ip/update-list) from my app's root directory, and it worked perfectly.

**Comment by danneu** [comment]
I listed it as a `devDependency` since it was something I only thought would be useful during development, i.e. after one has cloned the github repo rather than `npm install`ing it.

https://github.com/danneu/cloudflare-ip/blob/master/package.json#L23

I'll look into it.

**Comment by uniibu** [comment]
You listed 'fetch' https://www.npmjs.com/package/fetch , but you used 'node-fetch' https://www.npmjs.com/package/node-fetch
https://github.com/danneu/cloudflare-ip/blob/master/update-list.js#L6

**Comment by danneu** [comment]
Haha, good catch.
