### ISSUE TITLE
'::ffff' return true if app.proxy is enabled

### ISSUE THREAD

**Issue by uniibu** [danneu/cloudflare-ip#3]
Using koajs code below and assuming the ip is 180.4.3.1

```
const util = require('util');
const cf = require('cloudflare-ip');
const app = require('koa')();
app.proxy = true; 

app.use(function*(next) {
let remoteAddress = this.request.socket.remoteAddress; // returns ::ffff:180.4.3.1
assert(cloudflareIp(remoteAddress)); // true should be false
console.log(util.format('remoteAddress=%s'), remoteAddress)); 
// will log, remoteAddress=::ffff:180.4.3.1
yield next;
})
```

Well i know the solution is on the code, by simply doing 
`let remoteAddress = this.request.socket.remoteAddress.split(":").pop();`
should give me the ip address without the ::ffff, but the problem relies that any hexadecimal from (a,b,c,d,e,f) return true aswell:
https://tonicdev.com/5766b7313498bf1300e565f5/5766c4f80fc7bb1400405f5d

**Comment by danneu** [comment]
Interesting

http://www.tcpipguide.com/free/t_IPv6IPv4AddressEmbedding.htm
https://en.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses

Looks like the library I'm using to check IP addresses isn't very robust.

Wish I knew enough to quickly write my own mask validator, but not sure I have the energy. 😃

**Comment by danneu** [comment]
It works/parses now, but 180.4.3.1 isn't in cloudflare range so it returns false.
