### ISSUE TITLE
cloudflareIp('2400:cb00::0000::0000')  should be false

### ISSUE THREAD

**Issue by uniibu** [danneu/cloudflare-ip#5]
According to https://en.wikipedia.org/wiki/IPv6_address
-This two-colon replacement may only be applied once in an address, because multiple occurrences would create an ambiguous representation.
Therefor, cloudflareIp('2400:cb00::0000::0000') should be false

**Comment by danneu** [comment]
Fixed https://github.com/danneu/cloudflare-ip/commit/0207045e640b53e3fc38391bf97034f38da5c764
